version: '3.1'
services:
  server:
    image: girondi/super_container:latest
    hostname: server
    container_name: csd_server
    networks:
      csd_net:
        ipv4_address: 172.31.199.1
    cpuset: 40-55,152-167
    mem_limit: 64G
    mem_reservation: 8G
    deploy:
      resources:
        limits:
          cpus: 32
          memory: 64G
        reservations:
          #cpus: 4
          memory: 4G
          devices:
            - driver: nvidia
              #count: 1
              device_ids: [ "${GPU_ID}" ]
              capabilities: [gpu]
    volumes:
      - ./workspace:/workspace
      - ./home:/home/${DOCKERUSER}
    devices:
      - ${SERVER_IBDEV}
      #- /dev/infiniband/rdma_cm
    restart: unless-stopped
  client:
    image: girondi/super_container:latest
    hostname: client
    container_name: csd_client
    networks:
      csd_net:
        ipv4_address: 172.31.199.2
    cpuset: 96-111,208-223
    mem_limit: 64G
    mem_reservation: 8G
    devices:
      - ${CLIENT_IBDEV}
        #- /dev/infiniband/rdma_cm
    volumes:
      - ./workspace:/workspace
      - ./home:/home/${DOCKERUSER}
    restart: unless-stopped
      #  tcpdump_server:
      #image: mellanox/tcpdump-rdma 
      #command: tcpdump -i mlx5_2 -vvv -l -n 
      #privileged: true
      #network_mode: host
      #volumes:
      #- /dev/infiniband
      #privileged: true
networks:
  csd_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.199.0/24
          gateway: 172.31.199.254

